version: "3.9"

services:
  backend:
    build: ./realtime-backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./realtime-backend:/app
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    restart: always

  frontend:
    build: ./realtime-ui
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./realtime-ui:/app   # bind mount local folder to container
      - /app/node_modules
    depends_on:
      - backend
    restart: always


